stages:
  - build
  - lint_format
  - migrations
  - test
  - deploy


.base_ruff:
  stage: lint_format
  interruptible: true
  image:
    name: ghcr.io/astral-sh/ruff:0.11.6-alpine
  before_script:
    - ls -lah
    - ruff --version

Ruff Check:
  extends: .base_ruff
  script:
    - ruff check --output-format=gitlab

Ruff Format:
  extends: .base_ruff
  script:
    - ruff format --diff


Migrations:
  stage: migrations
  script: 
    - docker run --rm --network booking_net booking-api-image -c "alembic upgrade head"


Tests:
  stage: test
  script:
    - docker run --rm --network booking_net booking-api-image -c "alembic upgrade head; pytest -s -v"


Build Image:
  stage: build
  before_script: 
    - cp ${PROD_ENV} .env
    - cp ${TEST_ENV} .env-test
    - ls -lah
  script:
    - docker build -t booking-api-image .


Deploy App:
  stage: deploy
  script:
    - docker compose -f docker-compose-ci.yml up -d