stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  before-script: 
    - cp ${PROD-ENV} .env
    - cp ${TEST-ENV} .env-test
  script:
    - docker build -t booking-api-image .

deploy-job:
  stage: deploy
  script:
    - docker compose up -d