"""del hotels name

Revision ID: 37402ca20d54
Revises: 2eeede10a2f0
Create Date: 2025-03-18 15:04:11.613474

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "37402ca20d54"
down_revision: Union[str, None] = "2eeede10a2f0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("hotels", "name")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "hotels",
        sa.Column("name", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    )
    # ### end Alembic commands ###
