"""add users_v1

Revision ID: f8ff5acfd59a
Revises: 44ce3fa491fc
Create Date: 2025-03-20 09:30:58.788433

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f8ff5acfd59a"
down_revision: Union[str, None] = "44ce3fa491fc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("username", sa.String(length=200), nullable=False))
    op.add_column(
        "users", sa.Column("first_name", sa.String(length=200), nullable=False)
    )
    op.add_column(
        "users", sa.Column("last_name", sa.String(length=200), nullable=False)
    )
    op.drop_column("users", "name")


def downgrade() -> None:
    """Downgrade schema."""
    op.add_column(
        "users",
        sa.Column("name", sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    )
    op.drop_column("users", "last_name")
    op.drop_column("users", "first_name")
    op.drop_column("users", "username")
